---
- name: Super secret vault
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - ./vars/secrets.yml

  tasks:
    - name: Debug message
      debug:
        msg: "{{ user_password }}"
