---
- name: Install basic components and create a new user
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install basic packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - python
        - python-crypto
        - ansible

    - name: Create a new group for a new user
      group:
        name: demo
        state: present

    - name: Create a new user for this demo
      user:
        name: demo
        state: present
        group: demo

- name: Super secret ansible-vault demo
  hosts: all
  become: true
  become_user: demo
  gather_facts: false

  tasks:
    - name: Checkout this demo inside a VM
      git:
        repo: https://github.com/fabiogoma/ansible-vault.git
        dest: /home/demo/ansible-vault

    - name: Remove unnecessary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/demo/.ssh/id_rsa
        - /home/demo/.ssh/id_rsa.pub
        - /home/demo/ansible-vault/README.md
        - /home/demo/ansible-vault/Vagrantfile
        - /home/demo/ansible-vault/provisioning/main.yml
        - /home/demo/ansible-vault/provisioning/

    - name: Create hidden ssh directory
      file:
        path: /home/demo/.ssh/
        state: directory

    - name: Generate ssh key pair
      shell: ssh-keygen -t rsa -f '/home/demo/.ssh/id_rsa' -N ''
      changed_when: false
